# Generated by Django 6.0 on 2025-12-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedApp', '0002_alter_relationship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('sent', 'sent'), ('accepted', 'accepted')], default='sent', max_length=8),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
